server:
  port: 8080
  jwt_secret: "astraflow_jwt_secret_key_2025"

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  database: "astraflow"
  charset: "utf8mb4"
  parseTime: true
  loc: "Asia/Shanghai"   # 与docker-compose中的TZ保持一致